### ISSUE TITLE
Tradução notificação 

### ISSUE THREAD

**Issue by zedamoca** [ingbrzy/MA-XML-7.0-PORTUGUESE#10]
Quando recebemos uma chamada e a mesma não é atendida continua a aparecer missed call na notificação e não "chamada perdida"

**Comment by KcNirvana** [comment]
Boas.
Que telefone estás a usar e onde é que aparece?
Na app telefone?

**Comment by zedamoca** [comment]
Aparece quando não atendemos uma chamada e fica a notificação na Barra superior. Aparece missed call. No redmi 2 acho que está correcto.


Enviado a partir do Outlook para Android





On Mon, Nov 2, 2015 at 3:44 PM -0800, "KcNirvana" <notifications@github.com> wrote:
Boas.
Que telefone estás a usar e onde é que aparece?
Na app telefone?

---

**Comment by KcNirvana** [comment]
Boas...
Posta um screenshot para eu conseguir ver onde tenho de adicionar a traduçao.
Obrigado.

**Comment by zedamoca** [comment]
Enviado a partir do Outlook para Android





On Mon, Nov 2, 2015 at 4:06 PM -0800, "KcNirvana" <notifications@github.com> wrote:
Boas...
Posta um screenshot para eu conseguir ver onde tenho de adicionar a traduçao.
Obrigado.

---

**Comment by KcNirvana** [comment]
Tenta vir ao github e postar pk aqui n aparece nada...

**Comment by zedamoca** [comment]
Não percebo nada do GitHub mas vou tentar.


Enviado a partir do Outlook para Android





On Mon, Nov 2, 2015 at 4:22 PM -0800, "KcNirvana" <notifications@github.com> wrote:
Tenta vir ao github e postar pk aqui n aparece nada...

---

**Comment by zedamoca** [comment]
![screenshot_2015-11-02-22-50-22_com miui home](https://cloud.githubusercontent.com/assets/15620868/10902325/fe6fa4a4-81f3-11e5-8bdd-c967d90c4dd1.png)

**Comment by KcNirvana** [comment]
Boas...
Obrigado pelo screenshot.
Já detectei e já tá corrigido.
Se for lançadas as ROMs na sexta feira já devem ir com a tradução.
Abraço
