### ISSUE TITLE
Função editar nas fotos

### ISSUE THREAD

**Issue by zedamoca** [ingbrzy/MA-XML-7.0-PORTUGUESE#11]
Quando se carrega na opção editar em qualquer foto a última letra de cada legenda dos ícones inferiores aparece desalinhada.

**Comment by KcNirvana** [comment]
Boas...
Deve ser por causa dos rabiscos.
Posso passar a rabisco para tentar ver se deixa de estar desalinhado.

**Comment by zedamoca** [comment]
Aparece em todas as legendas nessa função editar.

A última letra aparece por baixo. Tenho um redmi 2 e um redmi note 2.


Enviado a partir do Outlook para Android





On Mon, Nov 2, 2015 at 3:43 PM -0800, "KcNirvana" <notifications@github.com> wrote:
Boas...
Deve ser por causa dos rabiscos.
Posso passar a rabisco para tentar ver se deixa de estar desalinhado.

---

**Comment by KcNirvana** [comment]
Sim eu sei, mas se verifcares em landscape so o rabiscos e que aparece desalinhado p isso deduzo que seja daí.
Amanha verifico e se fôr corrijo.
Obrigado

**Comment by zedamoca** [comment]
Ok. Em landscape por acaso não vi. A outra cena da missed call é no redmi note 2 esqueci-me de dizer. Obrigado.


Enviado a partir do Outlook para Android





On Mon, Nov 2, 2015 at 3:57 PM -0800, "KcNirvana" <notifications@github.com> wrote:
Sim eu sei, mas se verifcares em landscape so o rabiscos e que aparece desalinhado p isso deduzo que seja daí.
Amanha verifico e se fôr corrijo.
Obrigado

---

**Comment by zedamoca** [comment]
![screenshot_2015-10-28-07-57-51_com miui gallery](https://cloud.githubusercontent.com/assets/15620868/10902338/41b5ed86-81f4-11e5-8ea2-b2cca6456827.png)

**Comment by KcNirvana** [comment]
Boas,
Os rabiscos vão passar a "Riscar" deixando de estar desalinhado.
Na próxima versão já estará corrigido.
Obrigado e abraço
