### ISSUE TITLE
Tradução gradient na camara

### ISSUE THREAD

**Issue by zedamoca** [ingbrzy/MA-XML-7.0-PORTUGUESE#12]
Encontrei mais uma coisa que precisa de tradução. A opção "gradient" nos modos de fotografia pode ser substituído por "inclinação" que é a sua tradução mais correcta penso eu. E por conseguinte também a opção de "turn of gradient" por "Fechar modo inclinação"

![screenshot_2015-11-03-17-03-04_com android camera](https://cloud.githubusercontent.com/assets/15620868/10915115/3307218e-824d-11e5-9ddf-7e1cdd82e87d.png)

![screenshot_2015-11-03-17-03-21_com android camera](https://cloud.githubusercontent.com/assets/15620868/10915132/44f65be4-824d-11e5-8298-c24f09f8c576.png)

**Comment by KcNirvana** [comment]
Boas.
Adoptei a tua sugestão apenas em de Fechar modo pus desligar inclinação para nao haver desalinhamentos.
Obrigado.
Abraço

**Comment by zedamoca** [comment]
Hehe okapa. Eh pa o que for descobrindo vou postando de modo a tornar o sistema mais português possível.
