### ISSUE TITLE
Erros de tradução nos menus Bluetooth

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#14]
Quando se activa a função Bluetooth e se tenta comunicar com outro equipamento aparecem notificações em janela a informar o código de emparelhamento etc nesses quadros existe tradução em inglês e símbolos sobrepostos cifrões etc. Fiz dois prints screens se me for autorizado deixo os links mais tarde para melhor se verificar o problema.

**Comment by KcNirvana** [comment]
Boas rapaz...
Podes e deves postar os prints para se perceber melhor os bugs.
Convem tambem informar qual o telemovel.
Obrigado.
Abraço

**Comment by Lippe35** [comment]
Aqui vai:

http://imgur.com/a/97qsH

http://imgur.com/4pTNXyE

Redmi note 2 (Hermes)

Abraço

**Comment by KcNirvana** [comment]
Ok...
Diferentes traduções para diferentes dispositivos.
Amanhã corrijo.
Obrigado.
Abraço

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Quando actualizares valida sff.
Obrigado.

Abraço

**Comment by Lippe35** [comment]
Ok eu actualizo.

Entretanto existem pequenos bugs na tradução no menu acessibilidade em alguns respectivos submenus se quiseres reporto mais logo ou para a semana a tempo da nova actualização.

Obrigado 
Abraço

**Comment by KcNirvana** [comment]
Estes vão já na release de amanhã.
Se conseguires reportar esses erros até as 18, ainda vão na de amanhã senão só na próxima semana.

**Comment by Lippe35** [comment]
Ok eu reporto agora pensava que se tivesse que dar mais tempo para se juntar os patches às releases semanais

**Comment by KcNirvana** [comment]
Tudo depende da disponibilidade de quem traduz.
As roms são produzidas normalmente sexta feira de manhã, por isso convém que os erros sejam reportados até quinta feira à tarde ( no meu caso, noutros repos de tradução eles podem ter outros horários) para ir nessa rom de sexta

**Comment by Lippe35** [comment]
Se quiseres posso ajudar vou então abrir tópico de bug

**Comment by KcNirvana** [comment]
Obrigado :) 
Mas isto faz se tranquilamente é tipo um hobbie...
Mas ajudas muito a postar bugs, ainda por cima quando a tradução está preparada para a versão de Android 4.4 e como não tenho nenhum que tenha Android 5.x não consigo verificar todos os erros
