### ISSUE TITLE
Erros Tradução Menu Acessibilidade

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#15]
Definições - Definições Adicionais - Acessibilidade

Submenus em inglês:

High contraste text (Experimental)

Display

Colour inversion
(Experimental may affect performance)

Colour correction

No menu onde se dá Acessibilidade a programas neste csso instalei o Airdroid e quando vou para executar a Acessibilidade aparece um sub quadro onde em duas frases faltam 2 letras

Seguem imagens

http://imgur.com/BZqnnmn

http://imgur.com/Ma40JSN

http://imgur.com/CSsaE9XX

Obrigado

Abraço

**Comment by Lippe35** [comment]
3 link de imagem com erro fica correcção

http://imgur.com/CSsaE9X

**Comment by KcNirvana** [comment]
Tudo corrigido.
Obrigado
