### ISSUE TITLE
Erros de tradução no menu não pertubar

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#16]
Definições - Não Perturbar
Segue erros em anexo:

http://imgur.com/nh36Fj2

http://imgur.com/I2lgBiy

Obrigado

Abraço

**Comment by Lippe35** [comment]
Versão Redmi Note 2 (Hermes)

**Comment by KcNirvana** [comment]
Corrigido.
Obrigado.
Abraço
