### ISSUE TITLE
Erros Tradução 

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#17]

**Comment by KcNirvana** [comment]
Boas...
Os erros ficaram corrigidos?
Abraço

**Comment by Lippe35** [comment]
Boas, os erros de tradução ficaram corrigidos, parabéns pelo excelente trabalho. Queria entretanto reportar mais erros de tradução mas fiquei a meio e até abri este report mas desde que actualizei para a rom 5.11.5 a rede wifi perde autenticação de password apesar desta estar correcta queria reportar esta situação e não encontro sitio para me registar no forum europeu para participar o bug, tenho conta Mi e entro bem no forum Miui em ingles mas no europeu não tem como eu descobrir

Abraço

**Comment by KcNirvana** [comment]
Tens o Mi4C ne?
Também já ouvi falar disso no forum.
Mas não sei se será da rom Xiaomi.Eu se será mesmo da chinesa..

**Comment by Lippe35** [comment]
Não tenho um Redmi Note 2 saquei a versão Hermes hoje as traduções PT que corrigistes estão bem o problema ou alguma coisa ficou mal compilada ou o bug no wifi vem da rom original chinesa

**Comment by KcNirvana** [comment]
Quase que aposto que esse bug vem da rom chinesa...

**Comment by Lippe35** [comment]
Sim de certo será da ROM chinesa, aparentemente consegui resolver o bug pelo menos não necessito reiniciar o telf basta activar e desactivar o modo avião que o WIFI vai-se aguentando. Não me apetecia fazer downgrade por causa deste bug a tradução PT está excelente. Vou aproveitar que tenho WIFI e vou reportar os bugs de Tradução que entretanto descobri e nada tem haver com os que foram corrigidos

**Comment by Lippe35** [comment]
Definições - Definições Adicionais - Privacidade dentro de privacidade existem vários sub menus em inglês seguem imagens em anexo:

http://imgur.com/YZnqPHG

http://imgur.com/IUXh9ZZ

http://imgur.com/ABHdl76

No aplicativo telefone onde realizamos as chamadas em definições no menu definições submenu chamada em espera quando clicamos aparece um quadro com uma frase em inglês a dizer call settings mas aparece e desaparece tão rápido que é impossível tirar imagem

http://imgur.com/0IS8KoD

http://imgur.com/kdWiUJ8

Obrigado

**Comment by KcNirvana** [comment]
Boas...
Tudo corrigido para a próxima sexta-feira.
Diz me só uma coisa, já está também corrigido o bug das chamadas não atendidas?
Obrigado.
Abraço

**Comment by Lippe35** [comment]
Ficou impecável já aparece em Portugues. Basta só corrigir o bug do wifi pode ser que entretanto e à medida que mais pessoas actualizem se faça mais reports do problema.

Um abraço e bom fim de semana

**Comment by Lippe35** [comment]
Boas, aqui ficam mais bugs pode ser que ainda sejam corrigidos e entrem na versão 5.11.6 de 2° Feira

Na barra de atalhos quando se puxa para baixo com o dedo no ecrã no icon modo silêncio e deixando lá o dedo alguns segundos entramos no menu que tem sub menus em inglês

http://imgur.com/1w356NT

Em ferramentas Conta Mi

http://imgur.com/pFk2ME2

Entra-se na Nuvem Mi em baixo endereço web encontra-se incorrecto Sugestão (mi.com ou www.mi.com)

http://imgur.com/8ZpT7Qv

Igualmente na imagem de cima pode-se ver no sub menu cópia do ecrã inicial tem a palavra pra que se pode substituir por para

Em ferramentas menu Não Perturbar logo que se entra no cabeçalho de identificação do menu falta a letra R na palavra Pertubar

http://imgur.com/TgZkYN4

Obrigado

**Comment by Lippe35** [comment]
Para melhor identificar o 1 bug acima referido ir a Definições - Não Perturbar - Entrar no sub menu Permitir apenas excepções 

http://imgur.com/1w356NT

Dentro do Menu não Perturbar no sub menu Silenciar todos os distúrbios existem sub menus em inglês

http://imgur.com/aSuSb0ee

Obrigado

**Comment by Lippe35** [comment]
Correção do último link de imagem

http://imgur.com/aSuSb0ee

Obrigado

**Comment by Lippe35** [comment]
http://imgur.com/aSuSb0e

Foi desta copy past dá sempre erro :-)

**Comment by KcNirvana** [comment]
Boas tudo corrigido menos o i.mi.com que é o site da MiCloud.
Experimenta i.mi.com que ele leva te à cloud.
Obrigado.
Abraço

**Comment by Lippe35** [comment]
Como o link leva a um domínio chinês pensei que tivesse erro ou existisse em plataforma com lingua em inglês. Pronto é isso de resto tudo OK.

Abraço e Obrigado

**Comment by Lippe35** [comment]
Como o link leva a um domínio chinês pensei que tivesse erro ou existisse em plataforma com lingua em inglês. Pronto é isso de resto tudo OK.

Abraço e Obrigado

**Comment by Lippe35** [comment]
Boas,
No programa de segurança do MIUI no sub menu bateria as duas primeiras frases têm a palavra bateria uma com letra b minúscula e outra com B maiúsculo, por sugestão poderia ficar Bateria em maiúscula nas duas frases.

http://imgur.com/02zq09S

Em Ferramentas - Explorador - quando se escolhe onde se quer visualizar os ficheiros aparece a frase em inglês Phone Storage

http://imgur.com/Qeo4Ad2

Definições - Definições Adicionais - Armazenamento ainda aparece uma frase em inglês

http://imgur.com/Imuxt5N

Definições - Não Perturbar - Silenciar todos os distúrbios - no menu sounds ainda tem em inglês 

http://imgur.com/wuxnNXW

Ainda dentro do Menu sounds em call messages from tem em inglês

http://imgur.com/jQufElr

Obrigado

**Comment by Lippe35** [comment]
Na aplicação câmara em definições tem a frase em inglês time watermark poderá ser substituido por marca d'água data e hora

Pronto revi o que pude.

Obrigado

**Comment by KcNirvana** [comment]
Boas...
Tudo corrigido.
Abraço

**Comment by Lippe35** [comment]
Boas,
Igualmente no aplicativo de câmara em opções poderemos substituir disparo de explosão por disparo contínuo.

http://imgur.com/UaWSMD1

Obrigado abraço

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Abraço

**Comment by Lippe35** [comment]
Boas,
Na aplicação Vídeo em definições - definições de desenvolvimento:

Seleccionar substituir por Selecionar 

Versão (Stable) substituir por estável igual como está no submenu ou como Stable é uma expressão Universal para identificar um estado de um software no lugar de estável colocar Stable e deixar em ambos os lados Stable

Ainda dentro desde menu ir a Plugins do reprodutor de vídeo e substituir the por do

http://imgur.com/MhNU778

http://imgur.com/fHFc2yC

http://imgur.com/0uXAJAd

Obrigado Abraço

**Comment by KcNirvana** [comment]
Bons dias...
Tudo corrigido.
Obrigado.
Abraço

**Comment by Lippe35** [comment]
Boas, 
Definições - Definições Adicionais - Acessibilidade - correção de cor ainda existem menus inglês

http://imgur.com/VvW3Ams

http://imgur.com/DvZH13zz

Fica bem obrigado

**Comment by Lippe35** [comment]
http://imgur.com/DvZH13z

**Comment by KcNirvana** [comment]
Boas...
Tudo corrigido.
Abraço

**Comment by Lippe35** [comment]
Se tiveres dificuldade na tradução deste menu para PT são termos médicos para vários tipos de daltonismo por isso a possibilidade na alteração das cores. Tradução por ordem do menu em inglês:

Deuteranomalia (vermelho-verde)

Protanomalia (vermelho-verde)

Tritanomalia (azul-amarelo)

Obrigado
Abraço

Vi email agora enquanto fazia este comentário ok

**Comment by Lippe35** [comment]
Boas,
Aplicação temas entrar em conta Mi clicando do lado esquerdo superior do display dentro da aplicação temas depois em definições a frase Guardar no Sd colocar a palavra com D maiúsculo ficando Cartão SD

http://imgur.com/Ah8zVre

Obrigado

Abraço

**Comment by Lippe35** [comment]
Boas,
Changelog do dia 7 (814df77) hermes campo 53 linha 889 ficou Perturbarbar

De resto tudo ok vamos ver na rom de amanhã que vão adicionar a função esconder ficheiros no explorador e deve estar tudo em inglês, depois digo-te.

Obrigado fica bem

**Comment by Lippe35** [comment]
ba1b722 assim é que está correcto :-)

**Comment by Lippe35** [comment]
Esquece já vi que no log a seguir foi corrigido são tantas linhas que baralha lol

**Comment by davidsantos81** [comment]
pessoal, eu sei que não estou a perguntar no sitio certo, mas como ainda
não entendo muito bem disto, aqui vai a pergunta, podem me dizer qual a rom
a instalar num xiaomi redmi 2 pro de 2gb de ram e 16gb de rom?

obrigado e desculpem



Cumprimentos

David Santos

2015-11-12 7:09 GMT+00:00 Lippe35 <notifications@github.com>:

**Comment by KcNirvana** [comment]
Boas...
Acho que os Redmi são os HM2014** mas não sei qual a diferença de versões entre HM2014811 e HM2014813..

**Comment by Lippe35** [comment]
Diz-me que versão é que tens pré instada no teu telf em definições acerca do telefone e se tens o idioma em PT ou só inglês e chinês? Perante estas informações será mais fácil dizer-te a ROM indicada

Cumprimentos

**Comment by davidsantos81** [comment]
boas, obrigado pela rápida resposta.

Eu ainda não tenho o telemovel, comprei ontem e deve chegar ou hoje ou
amanha.

depois informo.

Um abraço



Cumprimentos

David Santos

No dia 12 de novembro de 2015 às 09:34, Lippe35 <notifications@github.com>
escreveu:

**Comment by Lippe35** [comment]
Tens que confirmar com os números que estão na página de ROM downloads e conforme o KcNirvana indicou ou esses códigos estão no equipamento ou na caixa mas em princípio será Hermes mas depois informa quando o receberes

**Comment by Lippe35** [comment]
Boas,
Se ainda der tempo para alterar, na aplicação telefone quando se manda apagar os registos de chamadas aparece seleccionar e na galeria de imagens substituir por selecionar igualmente.

Em Definições acessibilidade está uma frase em inglês e mais abaixo substituir inspeccionar por inspecionar

http://imgur.com/Kd9sWtN

http://imgur.com/Aws8AQE

http://imgur.com/EQPFf1q

http://imgur.com/QVqjAUN

http://imgur.com/pkpzVCI

Obrigado

**Comment by KcNirvana** [comment]
Boas...
Em relação aos "Inspeccionar e Seleccionar" a tradução está feita com base no português antes do acordo ortográfico, senão tinha que alterar toda a tradução.
Em relação à frase em Inglês diria que deve ser da aplicação CM Security porque não apanho essa frase em lado nenhum.

Abraço

![ao](https://cloud.githubusercontent.com/assets/12718890/11119600/97a3fee0-8942-11e5-98a1-a68ec4d094fb.png)

**Comment by Lippe35** [comment]
Ah ok e a frase deve ser mesmo do software tudo impecável já foi um bom avanço esta semana. O resto vai-se acrescentando fico feliz por ter ajudado

Abraço

**Comment by KcNirvana** [comment]
:)
Obrigado pelas correções.
Vou fechar este tópico.
Amanhã se detectares mais erros abre se um novo.

Abraço
