### ISSUE TITLE
Bugs\Sugestões Tradução ROM 5.11.12

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#18]
Boas,
Na aplicação temas ficou um ponto final na frase: Toque para fazer cópia de segurança

http://imgur.com/eAF32BS

Na aplicação câmara em definições Marca d'água poderia indicar que é relativamente a data e hora ficando como sugestão: Marca d'água data e hora

Em definições - Armanezamento permanece uma frase em inglês

http://imgur.com/nrrwC6w

Em definições -Definições Adicionais - Opções de Programador existem frases em inglês

http://imgur.com/uyKLh2e

http://imgur.com/SzLNfkW

Em definições - Não Perturbar - Silênciar todos os distúrbios está uma frase em inglês

http://imgur.com/JOYu91y

Na aplicação Telefone - Definições - chamada em espera - Aparece um sub quadro a dizer Call Settings A carregar Definições

Na aplicação Vídeos - Definições - Definições de desenvolvimento - Escolher versão aparece em chinês. Desapareceu Stable Beta Alpha (se não me engano era esta a ordem)

http://imgur.com/17qqMvX

Deixo antecipadamente estas informações porque vou instalar uma rom anterior à 5.11.5 devido ao bug do WiFi

Obrigado

**Comment by KcNirvana** [comment]
Boas...

Na aplicação temas ficou um ponto final na frase: Toque para fazer cópia de segurança
Corrigido

Na aplicação câmara em definições Marca d'água poderia indicar que é relativamente a data e hora ficando como sugestão: Marca d'água data e hora
Corrigido

Em definições - Não Perturbar - Silênciar todos os distúrbios está uma frase em inglês
Corrigido

Na aplicação Telefone - Definições - chamada em espera - Aparece um sub quadro a dizer Call Settings A carregar Definições
Podes explicar?

Na aplicação Vídeos - Definições - Definições de desenvolvimento - Escolher versão aparece em chinês. Desapareceu Stable Beta Alpha (se não me engano era esta a ordem)
Corrigido

Abraço

**Comment by Lippe35** [comment]
Boas,
quando se clica em chamada em espera aparece um pequeno quadro tipo roda pé tipo janela flutuante que diz a negrito

Call Settings
A carregar Definições (está frase não está a negrito) É cerca de 5 segundos é tão rápido que não tenho tempo de ir fazer o print screen.

Não te esqueças dos menus e sub menus do programador. Agora já vou mais descansado para o fim de semana já tenho WiFi :-)

**Comment by KcNirvana** [comment]
Boas...
Call Settings
A carregar Definições (está frase não está a negrito) É cerca de 5 segundos é tão rápido que não tenho tempo de ir fazer o print screen.
Já achei e já está corrigido.

Quanto aos menus programador só quando vir a tradução portuguesa da Google....
Não vou estar a inventar a roda...
:)

**Comment by Lippe35** [comment]
Boas,
essa da roda foi genial :-). Mas olha tive a verificar o idioma em espanhol e tem os menus de Programador traduzidos e percebe-se bem tens acesso ao idioma Espanhol? ou queres que te envie print screens? Ou fica tudo como está?

Abraço

**Comment by Edufex** [comment]
KcNirvana queria agradecer-te pelo excelente trabalho que estás a fazer.

Derivado aos meus horários já não me era possivel mais continuar a acompanhar a tradução.
Obrigado por continuares o meu trabalho e pelo esforço em o manter actualizado.

Abraço

**Comment by Edufex** [comment]
Bateria e desempenho.

Gerir utilização da bateria das aplicações está uma boa parte em chinês.
Não sei se com o google translator consegues alguma das traduções.

o telefone é o MI4C.( Versão Libra )

**Comment by KcNirvana** [comment]
Boas...
@Lippe35 
Esses são menus de programador do android 5.x, se os tivesse já tinha traduzido...
Se não te importares, mete aqui a tradução espanhola ou portuguesa que eu ou traduzo e passo ou apenas passo...
Obrigado :)
Abraço

@Edufex 
De nada rapaz...
Enquanto tiver tempo vou actualizando...
Podes me mostrar um screenshot do que está em chinês?
Obrigado.
Abraço

**Comment by Lippe35** [comment]
Boas,
sendo assim aqui vai as traduções que estavam em Inglês alterei o Idioma do telf para o Espanhol e com ajuda do tradutor Google traduzi do Espanhol para o Português: (se necessitares faço print screen dos menus de Programador em Espanhol)

Activar os atributos de inspeção de visualização

http://imgur.com/t5Y8V42

Activar o registo de Wi-Fi Detalhado

Transferência do Wi-Fi para telefone

Permitir sempre pesquisas do Wi-Fi

Registo de ficheiros por tamanho 

Seleccionar o tamanho do registo por ficheiros registados

http://imgur.com/Q7Lh7Gq

http://imgur.com/3Afiazh

Simular espaço de cor 

http://imgur.com/Jc7NHE8

este submenu dos termos de daltónico foram traduzidos a semana passada em princípio fica igual

http://imgur.com/jjviAaU

Desactivar o encaminhamento de áudio
(desactivar o roteamento automático dos preféricos de áudio USB)

Entretanto pode ser que ao analizares esta tradução ainda a consigas melhorar

Abraço

**Comment by Lippe35** [comment]
Boas,
Definições - Definições Adicionais - Privacidade - Proteção de privacidade frase:

http://imgur.com/L4g29I5

Ver padrão de desbloqueiol 

obrigado

**Comment by KcNirvana** [comment]
Boas...
Já tinha sido corrigido algures...
Abraço

**Comment by KcNirvana** [comment]
@Edufex 
As strings em xinês já foram passadas e vão corrigidas nesta versão.
@Lippe35 
Vemo nos para semana com novos erros ou não....
:)
Abraço

**Comment by Lippe35** [comment]
@KcNirvana Pera lá não feches a porta sem levares um abraço lol.

cumps

**Comment by Edufex** [comment]
Boas.

Mais uma vez obrigado pelo trabalho.

Abraço.

Efex
