### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by davidsantos81** [ingbrzy/MA-XML-7.0-PORTUGUESE#19]
pessoal, eu sei que não é o sítio certo, mas será que alguma alma generosa me pode ajudar a instalar a MIUI num galaxy s3 I9300 android 4.1.1.

agradecido se algum poder ajudar.

um abraço

**Comment by KcNirvana** [comment]
Boas...
No site da miui tens la roms portadas com flashing guide...
Podes smp experimentar...

http://en.miui.com/download-17.html

**Comment by davidsantos81** [comment]
Obrigado ja consegui ;)
Em 20/11/2015 21:20, "KcNirvana" <notifications@github.com> escreveu:

**Comment by davidsantos81** [comment]
já agora voces sabem qual a versão que tenho de fazer download para
actualizar a rom de um redmi 2 pro de 2gb de ram e 16gb de rom. e também de
um redmi note de 1gb de ram e 8 gb de rom?

obrigado novamente

Cumprimentos

David



Cumprimentos

David Santos

2015-11-22 22:38 GMT+00:00 KcNirvana <notifications@github.com>:

**Comment by KcNirvana** [comment]
Boas...
Vai a informações do dispositivo e vê quais os modelos para ver se te conseguimos ajudar melhor:
Não estranhes a imagem, tou a testar o Android 6.0 :)
![screenshot 23_11_2015 2_28_43 da tarde](https://cloud.githubusercontent.com/assets/12718890/11338952/e3f6296c-91ee-11e5-8e84-b0f9fd58396e.png)

**Comment by davidsantos81** [comment]
este é do redmi 2 pro, o do redmi note nao tenho aqui comigo de momento ![03eb9f85-068d-44e7-bc68-ff15262f7d5c](https://cloud.githubusercontent.com/assets/14250085/11339179/2f353b7e-91f0-11e5-9f94-13e970f3b49f.jpg)

**Comment by KcNirvana** [comment]
Boas...
A rom para esse e HM2014813 salvo erro...
Mas deixa alguem passar aqui e confirmar também...
@Lippe35 e @Edufex  conseguem confirmar?
Obrigado.
Abraço

**Comment by davidsantos81** [comment]
muito obrigado, fico a aguardar entao mais confirmações.

Obrigado



Cumprimentos

David Santos

No dia 23 de novembro de 2015 às 14:52, KcNirvana <notifications@github.com>
escreveu:

**Comment by Lippe35** [comment]
Boas,
O Redmi 2 de 2GB é a rom versão HM2014813
O Redmi Note tens que confirmar melhor por esta lista porque existem 2 modelos 

http://imgur.com/2KFZz5l

A lista está no forúm e a versāo se queres confirmar está no chassi do telf quando tiras a bateria

@KcNirvana também quero Android 6 para o meu Hermes lol

Abraço

**Comment by davidsantos81** [comment]
obrigado pela resposta.

Era realmente o que eu pensava ser e o que o @KcNirvana confirmou.

Porque eu tinha tirado a bateria do telemovel e em cima do lado esquerdo
estava o número 2014813 e na lista das roms estala lá essa tal com o número.

Agora o problema é com o Remi note, pois o redmi note que eu tenho é o 4G
mas com dual sim e na lista n vejo nenhum :(



Cumprimentos

David Santos

No dia 23 de novembro de 2015 às 15:14, Lippe35 <notifications@github.com>
escreveu:

**Comment by Lippe35** [comment]
Epa agora é que me tramaste lol também não sei vai ao google investigar :-)

**Comment by KcNirvana** [comment]
@Lippe35 @davidsantos81 
Eu diria que é o Gucci mas carece de validação...

**Comment by davidsantos81** [comment]
obrigado pessoal, nao sei que faça, já procurei mas n encontro nada, o que
poderá acontecer se eu instalar uma rom errada? :(



Cumprimentos

David Santos

2015-11-23 15:34 GMT+00:00 KcNirvana <notifications@github.com>:

**Comment by Lippe35** [comment]
Nas melhores das hipoteses não instala mas se instalar danifica o telf, diz-me o código que aparece no chassi quando tiras a bateria

**Comment by davidsantos81** [comment]
não o tenho aqui comigo, o telemovél é de um primo meu, logo a noite já
arranjo isso e depois coloco aqui.

Mais vale não arriscar. LOL

se entrar no site http://en.miui.com/download-218.html#370 à frente de onde
diz Redmi note, tem aí vários modelos e não faz referencia ao que eu falo,
mas sim de uma maneira geral o Redmi Note 4G Dual-SIM

assim sendo deve mesmo ser a gucci





Cumprimentos

David Santos

2015-11-23 15:47 GMT+00:00 Lippe35 <notifications@github.com>:

**Comment by Edufex** [comment]
Tambem não sei ao certo qual será.

Mas axo que este assunto não deveria ser analisado por aqui já que o mesmo só diz respeito á tradução da rom e não a outros assuntos.

Cumprimentos

**Comment by davidsantos81** [comment]
![2bedf6b6-e1c0-4dfb-98f0-07b889563994](https://cloud.githubusercontent.com/assets/14250085/11362278/8b3cc154-928a-11e5-9589-2c0dfe79f34f.jpg) boas pessoal, não quero ser chato mas há coisas que acontecem que tem de ser partilhadas e discutidas, reparem nessa imagem, ele tem dois  ficheiros certo? um retirado aqui do site da xiaomi.eu que é aquele ficheiro que eu instalo todas as semanas e o outro apareceu hoje quando estava a tentar saber se dava para saber qual o nome que estava no ficheiro aquando o download. Fui a app Actualizar, carreguei nos 3 pontinhos superior esquerdo e carreguei em transferir actualização ( isto já com o telemóvel actualizado)  então ele começou a fazer o download  e eu fui ao explorador e procurei para onde estava a ir o ficheiro ( na pasta do Download ou na pasta do downloaded_rom e aí estava ele... 
A minha pergunta é o seguinte, porque os nomes são diferentes? será outra rom? provém de onde? 

Obrigado pela atenção

@Edufex desculpa lá, eu sei que não é o sitio indicado, mas aqui é mais facil comunicar. 

Um abraço

**Comment by davidsantos81** [comment]
atenção que o ficheiro miui_cancro_mam.... não deixei fazer o download até ao fim. cancelei, por isso o tamanho ser menor

**Comment by KcNirvana** [comment]
Presumo que as dúvidas estejam tiradas.
Vou fechar o topico.
Segunda cá nos encontramos caso hajam bugs de tradução.
Grande abraço a todos
