### ISSUE TITLE
Rom 5.11.26

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#20]
Boas,
Aplicação controlo remoto quando se entra num equipamento emparelhado definições

http://imgur.com/gg6QbxL

Aplicação Autenticador Xiaomi quando se esquece a password tem caracteres e falta ? no fim da frase

http://imgur.com/8wOTAz5

Aplicação camara anti Banding

http://imgur.com/6ITuU3C

Cumps

**Comment by Lippe35** [comment]
Boas,

Definições -Tamanho do tipo de letra Prévisualizar sugestão: Pré-visualizar

Definições - Papel de parede 
Prévisualizar sugestão: Pré-visualizar

**Comment by Lippe35** [comment]
Boas,
Aplicação vídeo - Definições - Definições de Desenvolvimento - Versão Stable ou Developer quando é selecionada a versão Developer aparece um Sub quadro a soliciar uma senha e a palavra Juntar se deverá ser Juntar-se

**Comment by KcNirvana** [comment]
Boas @Lippe35 
Tudo corrigido com excepção do Anti Banding que não faço ideia de como traduzir.
Abraço

**Comment by Lippe35** [comment]
Boas,
A aplicação nativa Rádio FM está invertida porque tem o nome FM Rádio e não tem o acento na letra a e está toda em inglês consegues confirmar?

Abraço

**Comment by KcNirvana** [comment]
Não consigo confirmar, mas é capaz porque falta a tradução da apk FM.
Já corrigido

**Comment by Lippe35** [comment]
Boas,
Definições - Aplicações instaladas - Predifinidas substituir por Predefinidas quer no submenu e no menu transferidas execução etc

cumps

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Abraço

**Comment by Lippe35** [comment]
Boas,
tens conhecimento que após a instalação da rom 5.11.26 a aplicação nativa vídeo pede actualização e passa a chamar-se Mi Vídeo e está toda em inglês? Como não está embutida na própria rom sabes se vai ser actualizada ou corrigida? Se quiseres tenho screen shots e posso colocar aqui.

Cumps

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Essa actualização já vem desde a semana passada, e como a aplicação vídeo mantém-se não acredito que por base seja actualizada directamente na rom.

Abraço

**Comment by Lippe35** [comment]
Sim mas esta é uma nova versão saída no próprio dia da rom dia 26. Bom provavelmente vou desinstalar e ficar na versão antiga até haver novidades, de resto a rom para Hermes está muito porreira no PT-PT. O Anti-Banding é que está a causar dificuldades mas vou descobrir :-)

Abraço

**Comment by Lippe35** [comment]
Boas,
Aplicação Câmara - Qualidade de imagem sugestão: Standard por Média (padrão)

Prima e segure botão de Disparo sugestão: Disparo por do obturador
Disparo Contínuo sugestão de colocar letra C em minúscula

Frame da câmara Sugestão Standard 4:3 Padrão 4:3

Beautify sugestão por Beleza quer no menu das definições quer onde é activado idade e género

HHT sugestão: Noite 

http://imgur.com/NKfV21h

Definições - Acerca do telefone - Estado - Estado do serviço Sugestão: Voice por Voz

Definições - Aplicações instaladas - Limpar predefinições Sem predefinições definidas sugestão: Retirar . final da frase

P.S. - Anti banding não tem tradução para PT por sugestão se quiseres colocar a letra B em minúscula

Por esta semana é tudo :-)



http://imgur.com/NKfV21h

**Comment by KcNirvana** [comment]
Boas rapaz...

Aplicação Câmara - Qualidade de imagem sugestão: Standard por Média (padrão)
Corrigido

Prima e segure botão de Disparo sugestão: Disparo por do obturador
Corrigido

Frame da câmara Sugestão Standard 4:3 Padrão 4:3
Corrigido
Beautify sugestão por Beleza quer no menu das definições quer onde é activado idade e género
Passou a Embelezar

HHT sugestão: Noite
Corrigido

Definições - Acerca do telefone - Estado - Estado do serviço Sugestão: Voice por Voz
Corrigido

Definições - Aplicações instaladas - Limpar predefinições Sem predefinições definidas sugestão: Retirar . final da frase
Corrigido

Obrigado.
Grande abraço

**Comment by Lippe35** [comment]
Olha só dois pormenores que me esqueci de te dizer o 1 bug reportado lá em cima sobre o controlo remoto "por favor clique aqui se este controlador not funcionar bem" o p de por é em maisculo, outra coisa na aplicação camara tem: "Desligar Disparo contínuo" disparo a letra D é minuscula

Não precisas agradecer alguém tem que reportar os erros, dá trabalho mas não me importo:-)

**Comment by KcNirvana** [comment]
Boas...
Controlo remoto foi actualizado e essa frase já não existe.
Quanto à câmara foi corrigido.
E sim tenho que te agradecer porque basicamente és das poucas pessoas que reporta os erros...
Obrigado :)

Grande abraço
