### ISSUE TITLE
Rom 5.12.3

### ISSUE THREAD

**Issue by Lippe35** [ingbrzy/MA-XML-7.0-PORTUGUESE#21]
Boas,
APP Autenticador no ecrã principal o último parágrafo está muito em cima da opção continuar, dá para encurtar o espaço um pouco mais acima? Relativamente aos travessões dá para alterar por outros travessões um pouco mais pequenos? A frase: "Utilizado para Início de Sessão Seguro" Sugestão: Seguro por Segura

http://imgur.com/LDYBXt6

Ainda dentro desta aplicação clicando em cima em opções de adicionar conta aparece a seguinte imagem:

http://imgur.com/Ipc8IMu

Sugeria substituir por: deste quadrado no visor

APP Clima sugiro substituir Ensolarado por Céu Limpo Ensolarado é um termo PT-BR

http://imgur.com/0oF7Sry

Definições - Definições Adicionais - Opções de Programador ainda existem menus e sub menus em Inglês e alterar predifinido por predefinido

http://imgur.com/TOFbwD4

http://imgur.com/yaOHJUa

http://imgur.com/rXxi5Jz

http://imgur.com/PRFMWsn

http://imgur.com/rKujV6r

http://imgur.com/PpLnn8D

APP Vídeo quando se visualiza um conteúdo e se clica uma vez no ecrã aparece um menu do lado direito a dizer definições ficando a frase cortada e dividida em dois dá para retificar ou alongar o espaço para a frase caber inteira na mesma linha?

http://imgur.com/9gHmrdK

APP Kuaipan definições em espaço utilizado0% fica pegado à frase

http://imgur.com/DAWUOKi

Definições - Som e vibração - último menu colocar a palavra Áudio em letra minúscula

http://imgur.com/23nc0Jj

No Modo Criança como sugestão Início o 1° I ser minúsculo, Ecrã letra minúscula e não ter ponto final na frase

http://imgur.com/etwJiKn

Na Aplicação telefone definições retirar ponto final da frase que está na imagem

http://imgur.com/V9rzGIf

O mais correcto seria as frases dos submenus terem ponto final, mas por uma questão de facilitar e leitura e causar menus confusão à vista, o melhor é mesmo não ter a pontuação final nas frases

Aplicação Email Definições

http://imgur.com/KYJQzEW

http://imgur.com/G3JSt32

Não Pertubar alterar para Não Perturbar

Ao desinstalar uma aplicação surge a seguinte frase

http://imgur.com/n6AhWoI

Sugiro retirar ponto final

Quando se saí do Modo Avião informa que não tem cartão SIM até ficar registado

http://imgur.com/4u1iyJH

Sugestão de retirar o ponto final na frase

Galeria retirar o ponto final da frase

http://imgur.com/TdYTRoO

Na galeria ao partilhar uma foto aparecem vários programas com letras sobrepostas e com letras sumidas e tem a palavra inglês share to

http://imgur.com/sHhKZM1

http://imgur.com/gKuSjqv

http://imgur.com/xMv8Gh7

Dentro da galeria retirar ponto final nas frases

http://imgur.com/Lblz5nv

http://imgur.com/fYqNwLW

http://imgur.com/Tc1qSOi

Na Galeria tentar centrar a palavra vazio com a legenda conforme está nos outros menus

http://imgur.com/FdzXD2T

Na aplicação câmara função dos botões do volume substituir Disparador por Obturador

http://imgur.com/7wkmLo5

Definições - Acerca do telefone - Estado - Estado do serviço Sugestão: Voice por Voz

http://imgur.com/xGpDqIr

Em Definições - Mais - VPN retirar ponto final

http://imgur.com/f1ivN3G

APP Controlo remoto - definições menu Gamepad sobreposto do on/off

http://imgur.com/tDnxxms

Quando se entra num dispositivo emparelhado com o controlo remoto em definições o submenu de Reportar erro está em PT-BR

http://imgur.com/rgHKfcy

Sugiro: Se estiver com problemas ao usar este dispositivo, clique aqui para reportar esse problema

Acrescento que existe algum bug que impede que apareça o Menu seguinte para reportar o problema

Aplicação Gravador - Definições - Qualidade de Gravação sugiro substituir o til ~ por travessões

http://imgur.com/8IbO6y6

Obrigado um abraço e até para a semana se Deus quiser :-)

**Comment by KcNirvana** [comment]
Boas...
Vamos por partes:

APP Autenticador
APP Vídeo 
Só faço a tradução, a não ser que ponha algum tipo de diminuitivo

APP Kuaipan 
Definições - Som e vibração - último menu colocar a palavra Áudio em letra minúscula
No Modo Criança como sugestão Início o 1° I ser minúsculo, Ecrã letra minúscula e não ter ponto final na frase
Na Aplicação telefone definições retirar ponto final da frase que está na imagem
Aplicação Email Definições
Ao desinstalar uma aplicação surge a seguinte frase
Quando se saí do Modo Avião informa que não tem cartão SIM até ficar registado
Em Definições - Mais - VPN retirar ponto final
Definições - Definições Adicionais - Opções de Programador ainda existem menus e sub menus em Inglês e alterar predifinido por predefinido
Tudo Corrigido

**Comment by Lippe35** [comment]
Boas,
só foi corrigido o que escrevestes ou tudo o resto que eu reportei? Claro excepto APP Autenticador APP Vídeo. Apenas dou sugestões do que vejo pois não sei por dentro o trabalho de tradução e o que pode ser alterado ou não só isso

**Comment by KcNirvana** [comment]
@Lippe35 
APP Clima sugiro substituir Ensolarado por Céu Limpo Ensolarado é um termo PT-BR

http://imgur.com/0oF7Sry

Tens 2 hipóteses para talvez uma mesma tradução:
Clear - Céu limpo 
Sunny - Ensolarado

Que sugeres?

APP Controlo remoto - definições menu Gamepad sobreposto do on/off
Não posso fazer nada que não seja talvez encurtar a tradução

Na Galeria tentar centrar a palavra vazio com a legenda conforme está nos outros menus
Não posso fazer nada...

Aplicação Gravador - Definições - Qualidade de Gravação sugiro substituir o til ~ por travessões
Não é traduzível...

**Comment by KcNirvana** [comment]
@Lippe35 
Na galeria ao partilhar uma foto aparecem vários programas com letras sobrepostas e com letras sumidas e tem a palavra inglês share to

http://imgur.com/sHhKZM1

http://imgur.com/gKuSjqv

http://imgur.com/xMv8Gh7

Neste não estou a apanhar esse "Share too"...
Como é que vais para lá?

**Comment by Lippe35** [comment]
É entrando na galeria e querendo partilhar uma foto ou imagem é que aparece esse menu. Mas deixa estar até porque o programa meteorológico da Mi nunca acerta com o tempo está nublado e ele diz Ensolarado
