### ISSUE TITLE
Alinhamento de texto

### ISSUE THREAD

**Issue by zedamoca** [ingbrzy/MA-XML-7.0-PORTUGUESE#23]
Quando se acede a um link através de um a mensagem em que dá a hipótese de escolher uma opção, na opção navegador o R aparece desalinhado com o resto. Isto no redmi 2
Cumps

![screenshot_2015-12-06-17-40-46_android](https://cloud.githubusercontent.com/assets/15620868/11614702/0ea4ec7c-9c42-11e5-85ad-727191c4a5c1.png)

**Comment by KcNirvana** [comment]
Boas...
A única coisa que podemos fazer é mudar a tradução...
Abraço

**Comment by zedamoca** [comment]
Browser por exemplo :)

**Comment by Lippe35** [comment]
Boas,
Os nomes das Apps não podem ser alterados (Ex: Adobe Reader) A questão é que os menus ficaram disposto de uma forma horizontal e não na vertical como anteriormente. Poderá ser corrigido futuramente :-)

**Comment by zedamoca** [comment]
Okapa. Fazemos tudo para melhorar a tradução.
