### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by davidsantos81** [ingbrzy/MA-XML-7.0-PORTUGUESE#24]
Boas, VCS já viram o erro de tradução no despertador?
![screenshot_2016-03-05-15-52-34_com android deskclock](https://cloud.githubusercontent.com/assets/14250085/13548570/381befd4-e2eb-11e5-9944-129b752b199a.png)

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Obrigado.
Abraço
