### ISSUE TITLE
Tradução Redmi2 2Gb (2014813) 

### ISSUE THREAD

**Issue by tonirai** [ingbrzy/MA-XML-7.0-PORTUGUESE#25]
Encontrei os seguintes itens por traduzir:
![picsart_03-08-01 37 58](https://cloud.githubusercontent.com/assets/17724780/13603481/67b6df3c-e535-11e5-8295-cbe0352f0c64.jpg)
![picsart_03-08-01 36 38](https://cloud.githubusercontent.com/assets/17724780/13603485/725beaa4-e535-11e5-97fa-7b43c0ef360c.jpg)

**Comment by KcNirvana** [comment]
Boas...
Corrigido.
Obrigado.
Abraço
