### ISSUE TITLE
GPS and Cell Broadcast 

### ISSUE THREAD

**Issue by Mainframe25** [ingbrzy/MA-XML-7.0-PORTUGUESE#26]
GPS takes to mutch time to catch signal and sometimes only starts working after reboot. 

In my Mi4, I keep getting a cell broadcast alarm when travelling (My Mi3 doesn't do this).

**Comment by KcNirvana** [comment]
Hello mate...
This is the portuguese translation repo, not xiaomi bugs.
Please report the bugs on xiaomi.eu or official forum en.miui.com.
Thank you
Regards
