### ISSUE TITLE
Tradução Redmi2 2Gb (2014813)

### ISSUE THREAD

**Issue by tonirai** [ingbrzy/MA-XML-7.0-PORTUGUESE#27]
Olá, a rom Android 5.1 está muito boa, não detecto erros, parabéns. 
Apenas uma coisa cosmética, penso que devida ao espaço ocupado pela tradução. 
Reduzindo o espaçamento nos itens finais como entre os 2 primeiros, penso que resolverá. 

Hi, the 5.1 rom is very good, I can't detect errors, congratulations. 
Just a cosmetic thing, I think due to the space used by the translation. 
Reducing the spacing between the final items, as between the fist 2 items, I think will solve it. 

![picsart_03-31-03 36 24](https://cloud.githubusercontent.com/assets/17724780/14164269/de8cfeee-f6f5-11e5-9f4c-e5bd6f078d08.jpg)

**Comment by KcNirvana** [comment]
Boas...
Aqui só traduzimos...
Mas mesmo em inglês, ocorre o mesmo espaçamento...
![save_20160331_095847](https://cloud.githubusercontent.com/assets/12718890/14170840/a52e58be-f727-11e5-9219-4149c12bd519.jpeg)
Por isso não deve haver nada que possa fazer.
Obrigado.

Abraço
