### ISSUE TITLE
Missed Calls Menu

### ISSUE THREAD

**Issue by Mainframe25** [ingbrzy/MA-XML-7.0-PORTUGUESE#29]
Despite the system language chosen, when there is a missed call, the missed call indication is always in English.

![screenshot_2016-04-03-09-53-03_com miui home](https://cloud.githubusercontent.com/assets/12008021/14232313/5d21a808-f99f-11e5-8447-21f364d78bb2.png)

**Comment by KcNirvana** [comment]
Boas...
Qual e o telemovel?
Abraço

**Comment by Mainframe25** [comment]
Ola bom dia,

 

O tlm é um Mi4.

 

Cumprimentos

 

De: KcNirvana [mailto:notifications@github.com] 
Enviada: domingo, 3 de Abril de 2016 13:29
Para: ingbrzy/MA-XML-7.0-PORTUGUESE
Cc: Mainframe25
Assunto: Re: [ingbrzy/MA-XML-7.0-PORTUGUESE] Missed Calls Menu (#29)

 

Boas...
Qual e o telemovel?
Abraço

**Comment by KcNirvana** [comment]
Boas...
Isto erro é só referente à 6.1.31 correcto?
É que por acaso tenho um Mi4 e garanto que está tudo em PT.
![Uploading Screenshot_2016-04-05-10-32-59_com.miui.home.png…]()
![Uploading Screenshot_2016-04-05-10-33-18_com.android.settings.png…]()

Abraço

**Comment by Mainframe25** [comment]
Boas, 

 

Não, só me acontece agora que instalei a 6.3.31.

A mesma que não tem português (Portugal) disponível nas config.

 

Cumps

 

De: KcNirvana [mailto:notifications@github.com] 
Enviada: terça-feira, 5 de Abril de 2016 10:42
Para: ingbrzy/MA-XML-7.0-PORTUGUESE
Cc: Mainframe25
Assunto: Re: [ingbrzy/MA-XML-7.0-PORTUGUESE] Missed Calls Menu (#29)

 

Boas...
Isto erro é só referente à 6.1.31 correcto?
É que por acaso tenho um Mi4 e garanto que está tudo em PT.
[Uploading Screenshot_2016-04-05-10-32-59_com.miui.home.png…]()
[Uploading Screenshot_2016-04-05-10-33-18_com.android.settings.png…]()

Abraço

**Comment by KcNirvana** [comment]
Então esse erro é por causa de estares no idioma Português ( Brasil ).
Problema no repositório deles.
Aguarda pela próxima developer que este problema do Português ( Portugal ) já deverá estar corrigido.
Obrigado pelo report.
Abraço

**Comment by davidsantos81** [comment]
boas, eu tenho o mesmo problema, o telemóvel está todo em inglês. não aparece a opção de Português de Portugal
