### ISSUE TITLE
Chinês 

### ISSUE THREAD

**Issue by davidsantos81** [ingbrzy/MA-XML-7.0-PORTUGUESE#30]
![screenshot_2016-05-10-11-48-38_com android calendar](https://cloud.githubusercontent.com/assets/14250085/15144242/198513b8-16a6-11e6-88eb-1f63f8929e5e.png)

**Comment by davidsantos81** [comment]
![screenshot_2016-05-10-11-48-38_com android calendar](https://cloud.githubusercontent.com/assets/14250085/15144257/314c403e-16a6-11e6-8dc1-51a7b09dd20a.png)

**Comment by KcNirvana** [comment]
Boas...
Não costumo traduzir do chinês porque não sei o que está realmente escrito.
Vê lá se isto te faz sentido:
Subscrever páginas do calendário com imagens maiores. Para o ajudar a poupar tráfego, foi definido como "Apenas sincronizar em Wi-Fi"
Obrigado.
Abraço

**Comment by Edufex** [comment]
Boas KcNirvana o que eu fazia era  meter no google tradutor  e depois tentava organizar as palavras de maneira a fazerem sentido.

Subscrever páginas do calendário com imagens maiores. Para o ajudar a poupar dados, foi definido para "Apenas sincronizar em Wi-Fi"

Não sei se desta maneira ficará melhor..deixo ao teu critério.

**Comment by KcNirvana** [comment]
Por isso é que não gosto de traduzir do chinês...
:)
Sugestão aceite...
Obrigado.
Grande abraço
