### ISSUE TITLE
IMPRESSÃO DIGITAL - CRASH

### ISSUE THREAD

**Issue by SirAlmeida** [ingbrzy/MA-XML-7.0-PORTUGUESE#31]
Boa tarde.
Já comuniquei ao membro responsável pela tradução o problema, mas penso que deveria meter aqui pois várias pessoas devem ter o mesmo problema.
Na versão 6.5.26, quando clico em "Impressão digital 1", ou qualquer outro número de impressão digital, as definições crasham.
O problema está no número máximo de carateres... "Impressão digital 1 -> 19 carateres, incluindo espaços". O número máximo é 15.
Assim, pedia para que este problema se resolvesse. Se o problema for só meu, peço desculpa então, mas isto parece-me um erro do MIUI.
Obrigado.

**Comment by KcNirvana** [comment]
Boas...
Primeiro peço te que verifiques com o idioma en Inglês.
Se em Inglês não houver erros entao efectivamente e da tradução.
Peço te é screenshots para se saber onde alterar.
Abraço

**Comment by SirAlmeida** [comment]
Boa noite.
Em inglês não há erros!
Mas quer screenshots do quê? Não percebi muito bem, desculpe.
Abraço.

**Comment by KcNirvana** [comment]
Do ecrã em inglês da impressão digital onde em português dá erro.
Senão não sei onde tenho de corrigir

**Comment by SirAlmeida** [comment]
Boa tarde. 
Em princípio só irei conseguir fazer isso amanhã, hoje nem vou estar com o meu MI5.
Mas a partir daí posso fornecer toda a informação. Mas conheço um colega meu que tem o mesmo problema, já lhe mandei uma mensagem para ver se me arranja uns prints com o necessário.

**Comment by KcNirvana** [comment]
Boas...
Não há pressa...
Afinal já saiu a versão 6.5.30 para o Mi5 e isto só vai estar corrigido na próxima versão que já é Miui8

**Comment by SirAlmeida** [comment]
Mas resumindo.
Tiro um print em português de como está o nome das impressões digitais, um print das definições a crasharem ao clicar, um print com o MIUI em inglês a dizer "Fingerprint 1" e um print a conseguir aceder. Certo?
A 6.5.30 é a China Dev Rom da miui.com, mas esta não irá sair na xiaomi.eu, certo? A próxima só mesmo a alpha miui 8, certo?
Obrigado.

**Comment by Lippe35** [comment]
Que confusão de issue :-)

**Comment by SirAlmeida** [comment]
http://prntscr.com/bad7db - Aqui temos a página das impressões digitais em português.
http://prntscr.com/bad7jx - Ao clicar, primeiro fica uma página em branco.
http://prntscr.com/bad7ql - Depois, as definições crasham...

Ao mudar o MIUI para inglês:
http://prntscr.com/bad81f - Aqui temos a página das impressões digitais em português e **1 A INGLÊS!**
http://prntscr.com/bad8vp - E como se pode ver, em inglês, podemos editar!

O problema, volto a dizer, está no número de carateres que "Impressão digital1" ocupa. O máximo é 15, se não me engano.

ESPERO QUE O PROBLEMA ESTEJA MAIS CLARO!
Obrigado.

**Comment by KcNirvana** [comment]
Bom dia.
Problema corrigido para a próxima versão.
Obrigado.
Abraço
