### ISSUE TITLE
notification bar shortcuts are in English

### ISSUE THREAD

**Issue by Mainframe25** [ingbrzy/MA-XML-7.0-PORTUGUESE#6]
After MIUI Weekly ROM Releases 5.4.3, notification bar shortcuts are not translated to portoguese and remain in English

**Comment by Edufex** [comment]
Sorry for that.
My time is now reduce to update portuguese translation.
If some one can put the news string in portuguese folders i  translate .
I need help for that.
Once i have ask for help in that fuction but some  one refuse to help me and so there is the result.
Just put in the folder the new string and i do he rest.

**Comment by ingbrzy** [comment]
pushed latest EN strings to the repo...

**Comment by x1704e** [comment]
I can help by translating a bit and checking the strings that already have translations, if you'd like. I have spotted a few small mistakes. However, I'm not sure how to do so.

**Comment by Edufex** [comment]
Thanks

**Comment by Mainframe25** [comment]
I can help to translate a bit if you want, but i'm not shure how to do so.

**Comment by Edufex** [comment]
I think is ok now the notifications ?
