### ISSUE TITLE
Security Clean Translations

### ISSUE THREAD

**Issue by KcNirvana** [ingbrzy/MA-XML-7.0-PORTUGUESE#9]
Hello,
If you go to the app Security, and click on Clean button all the translations are in English.
Also in v6 5.6.25 they introduce a button in Notifications ( Manage Settings ) that are not translated too.
Thank you
Best regards

**Comment by x1704e** [comment]
I would be able to help if I knew how to insert the new strings into wherever I need to insert them. If it's easy enough to explain, could you help me out, @ingbrzy?

**Comment by ingbrzy** [comment]
@x1704e added all what you missed https://github.com/ingbrzy/MA-XML-6.0-PORTUGUESE/commit/6ed30569a06b4b475b3d63581c24689fa277bb78

**Comment by ingbrzy** [comment]
@x1704e @Edufex here are todays changes https://github.com/Acid-miuipolskapl/v6-XML-Compare/commit/07001f6b7d066edb3e2abc68bea395a1a4f2b412

you can track all daily changes here and add them to your repo https://github.com/Acid-miuipolskapl/v6-XML-Compare/commits/master

check just first commit on each day...

**Comment by KcNirvana** [comment]
When you clear all the apps the string after is not tranlasted as well
![screenshot_2015-07-01-10-06-19](https://cloud.githubusercontent.com/assets/12718890/8451249/ce846382-1fd9-11e5-9d76-e51ba5f441e1.png)

**Comment by davidsantos81** [comment]
definições -> definições adicionais-> acessibilidade-> Serviços is in Chinise language 5.9.17 beta

**Comment by KcNirvana** [comment]
@davidsantos81 
Hello.
Where is the bug because I can't see it.

![screenshot_com android settings_2015-09-24-11-41-39](https://cloud.githubusercontent.com/assets/12718890/10071592/db30359a-62b2-11e5-9513-12fa4b3475f7.png)

**Comment by davidsantos81** [comment]
Em 24/09/2015 11:53, "KcNirvana" <notifications@github.com> escreveu:

**Comment by KcNirvana** [comment]
@davidsantos81 
You replied in blank

**Comment by davidsantos81** [comment]
The problem is solved.,thanks

Enviado do meu iPad

No dia 24/09/2015, às 13:23, KcNirvana <notifications@github.com> escreveu:
